<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZihalTo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZihalTo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZihalTo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZihalTo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZihalTo\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZihalTo',
    'container.build_id' => 'ecb65612',
    'container.build_time' => 1582030440,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZihalTo');
